// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VigiShield.Infrastructure.Persistence;

#nullable disable

namespace VigiShield.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VigiShield.Domain.Entities.AlertConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AggressionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ClimbingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ForcedAccessEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("NighttimeEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("NighttimeStart")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("TailgatingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("TailgatingThresholdSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("UnknownPersonEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("WhatsAppEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique();

                    b.ToTable("AlertConfigs");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.AuthorizedFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPathsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("AuthorizedFaces");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.CameraConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CameraIp")
                        .HasColumnType("text");

                    b.Property<string>("CameraPassword")
                        .HasColumnType("text");

                    b.Property<string>("CameraPath")
                        .HasColumnType("text");

                    b.Property<int>("CameraPort")
                        .HasColumnType("integer");

                    b.Property<string>("CameraUsername")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomHlsUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamKey")
                        .HasColumnType("text");

                    b.Property<string>("StreamMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("CameraConfigs");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMonitoringPaused")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PrimaryUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecurityEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SecurityEventId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageCapturePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsNighttime")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonName")
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoClipPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.AlertConfig", b =>
                {
                    b.HasOne("VigiShield.Domain.Entities.Household", "Household")
                        .WithOne("AlertConfig")
                        .HasForeignKey("VigiShield.Domain.Entities.AlertConfig", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.AuthorizedFace", b =>
                {
                    b.HasOne("VigiShield.Domain.Entities.Household", "Household")
                        .WithMany("AuthorizedFaces")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.CameraConfig", b =>
                {
                    b.HasOne("VigiShield.Domain.Entities.Household", "Household")
                        .WithMany("CameraConfigs")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("VigiShield.Domain.Entities.Household", "Household")
                        .WithMany("Invitations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("VigiShield.Domain.Entities.Household", "Household")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VigiShield.Domain.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VigiShield.Domain.Entities.SecurityEvent", "SecurityEvent")
                        .WithMany()
                        .HasForeignKey("SecurityEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("Recipient");

                    b.Navigation("SecurityEvent");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.SecurityEvent", b =>
                {
                    b.HasOne("VigiShield.Domain.Entities.Household", "Household")
                        .WithMany("Events")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.User", b =>
                {
                    b.HasOne("VigiShield.Domain.Entities.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("VigiShield.Domain.Entities.Household", b =>
                {
                    b.Navigation("AlertConfig");

                    b.Navigation("AuthorizedFaces");

                    b.Navigation("CameraConfigs");

                    b.Navigation("Events");

                    b.Navigation("Invitations");

                    b.Navigation("NotificationLogs");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
